# 服务端口号
server:
  port: 8101
spring:
  application:
    # 集群配置，eureka服务端，的此名称要相同
    name: eureka-server
eureka:
  instance:
    # eureka服务端的注册中心ip
    hostname: 127.0.0.1
  client:
    serviceUrl:
      # 注册地址，集群配置时设置为其它的eureka地址，三个也是一样的，配置多个地址，用逗号隔开
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/
    # 是因为自己是注册中心，不需要将自己注册给注册中心(对于eureka-server来说)，设置为false(集群配置设置为true)
    register-with-eureka: true
    # 因为自己是注册中心，不需要去检索服务信息，集群时设置为true
    fetch-registry: true