# order项目端口号
server:
  port: 8000

spring:
  application:
    # 服务别名，注册到eureka注册中心名称
    name: member
eureka:
  client:
    service-url:
      # 当前服务注册到eureka服务地址，配置在多个eureka上要写多个地址，但是只会在一个eureka上显示，当此eureka挂了后，会在另一个显示
      defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/
    # 需要将自己注册到eureka上
    register-with-eureka: true
    # 需要检索服务
    fetch-registry: true
  # 心跳检测与持续时间
  instance:
    # client向server发送心跳时间间隔，单位s(client告诉server自己会按照该规则)
    lease-renewal-interval-in-seconds: 1
    # server在收到最后一次心跳之后的等待时间上限，单位s，超过则剔除(client告诉server自己按照此规则)
    lease-expiration-duration-in-seconds: 2



