# 服务端口号
server:
  port: 8100
eureka:
  instance:
    # 注册中心ip
    hostname: 127.0.0.1
  client:
    serviceUrl:
      # 注册地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 是因为自己是注册中心，不需要将自己注册给注册中心(对于eureka-server来说)，设置为false(集群配置设置为true)
    register-with-eureka: false
    # 因为自己是注册中心，不需要去检索服务信息
    fetch-registry: false