# order项目端口号
server:
  port: 8001
  tomcat:
    # tomcat最大线程数
    max-threads: 10

spring:
  application:
    # 服务别名，注册到eureka注册中心名称
    name: order
  cloud:
  # 注册中心为zk，添加zk依赖，启动类添加@EnableDiscoveryClient注解，
#    zookeeper:
#      # zk注册地址
#      connect-string: 127.0.0.1:2181

    # 使用consul作为注册中心，添加依赖，启动类添加@EnableDiscoveryClient注解，
#    consul:
#      # consul注册中心地址
#      host: localhost
#      # consul注册中心端口号
#      port: 8500
#      discovery:
#        # 服务地址直接为ip地址(写本模块要注册到consul的IP地址)，默认情况下服务注册到中心地址随机生成英文
#        hostname: 192.168.1.7
eureka:
  client:
    service-url:
      # 当前服务注册到eureka服务地址，配置在多个eureka上要写多个地址，但是只会在一个eureka上显示，当此eureka挂了后，会在另一个显示
      defaultZone: http://localhost:8100/eureka/,http://localhost:8101/eureka/
    # 需要将自己注册到eureka上
    register-with-eureka: true
    # 需要检索服务
    fetch-registry: true

##整合Hystrix
#feign:
#  hystrix:
#    enabled: true
##设置feign客户端超时时间

##sc feign默认支持ribbon
ribbon:
  # 建立连接所用的时间，使用网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源的时间
  ConnectTimeout: 5000


#feign的使用查看com.xyb.feign.MemberApiFeign
#restTemplate的使用，查看com.xyb.api.controller.OrderApiController
#DiscoveryClient的使用，根据服务名，获取注册中心上对应服务名的信息，查看类com.xyb.api.controller.OrderApiController


